# fly.toml app configuration file generated for fedi-canvas on 2023-09-12T20:17:05+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fedi-canvas"
primary_region = "mad"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
